#!/bin/sh
. test/lib.sh

begin "Handles empty table cells"
scdoc <<EOF >/dev/null
bug-example(1)

[[ *Foo*
:- 
:-
EOF
end 0

begin "Disallows differing row lengths"
scdoc <<EOF >/dev/null
bug-example(1)

[-
:-
:-
|-
:-
|-
:-
:-
EOF
end 1

begin "Escapes hyphens in table cells"
scdoc <<EOF | grep '^\\-\\-tab \\-t \\-3 long\\-term$' >/dev/null
test(8)

|[ --tab -t -3 long-term

EOF
end 0
