image: alpine/edge
packages:
- flex
- bison
sources:
- https://git.sr.ht/~sircmpwn/scdoc
secrets:
- 52022781-b772-4d8d-b7fe-0d962a4947b6
tasks:
- build: |
    cd scdoc
    make
- check: |
    cd scdoc
    make check
